DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS shows;
DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS sections;
DROP TABLE IF EXISTS auditoriums;
DROP TABLE IF EXISTS cinemas;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS video_format;
DROP TYPE IF EXISTS audio_format;
DROP TYPE IF EXISTS show_status;
DROP TYPE IF EXISTS availability_status;
DROP TYPE IF EXISTS booking_status;
DROP TYPE IF EXISTS payment_status;
