// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	go_geom "github.com/twpayne/go-geom"
)

type Booking struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"userId"`
	ShowID           uuid.UUID `json:"showId"`
	TotalAmount      int64     `json:"totalAmount"`
	Status           string    `json:"status"`
	PaymentReference string    `json:"paymentReference"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type BookingItem struct {
	ID        uuid.UUID `json:"id"`
	BookingID uuid.UUID `json:"bookingId"`
	SeatID    uuid.UUID `json:"seatId"`
	Price     int64     `json:"price"`
	CreatedAt time.Time `json:"createdAt"`
}

type City struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Format struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type Movie struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	LanguageCode   string         `json:"languageCode"`
	Synopsis       *string        `json:"synopsis"`
	ReleaseDate    time.Time      `json:"releaseDate"`
	RuntimeMinutes *int32         `json:"runtimeMinutes"`
	PosterUrl      *string        `json:"posterUrl"`
	TrailerUrl     *string        `json:"trailerUrl"`
	CreatedAt      time.Time      `json:"createdAt"`
	Certification  *string        `json:"certification"`
	Rating         pgtype.Numeric `json:"rating"`
}

type Screen struct {
	ID         uuid.UUID `json:"id"`
	TheaterID  uuid.UUID `json:"theaterId"`
	Name       string    `json:"name"`
	TotalSeats int32     `json:"totalSeats"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type ScreenFormatCapability struct {
	ScreenID uuid.UUID `json:"screenId"`
	FormatID uuid.UUID `json:"formatId"`
}

type Seat struct {
	ID         uuid.UUID `json:"id"`
	ScreenID   uuid.UUID `json:"screenId"`
	SeatRow    string    `json:"seatRow"`
	SeatNumber int32     `json:"seatNumber"`
	SeatTypeID uuid.UUID `json:"seatTypeId"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"createdAt"`
}

type SeatAllocation struct {
	ShowID    uuid.UUID  `json:"showId"`
	SeatID    uuid.UUID  `json:"seatId"`
	BookingID *uuid.UUID `json:"bookingId"`
	IsBooked  bool       `json:"isBooked"`
}

type SeatType struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Show struct {
	ID        uuid.UUID `json:"id"`
	MovieID   uuid.UUID `json:"movieId"`
	ScreenID  uuid.UUID `json:"screenId"`
	StartTime time.Time `json:"startTime"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	FormatID  uuid.UUID `json:"formatId"`
}

type ShowSeatPricing struct {
	ShowID     uuid.UUID `json:"showId"`
	SeatTypeID uuid.UUID `json:"seatTypeId"`
	Price      int64     `json:"price"`
}

type Theater struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	Address      string        `json:"address"`
	Location     go_geom.Point `json:"location"`
	ContactPhone *string       `json:"contactPhone"`
	ContactEmail *string       `json:"contactEmail"`
	Status       string        `json:"status"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdatedAt    time.Time     `json:"updatedAt"`
	CityCode     string        `json:"cityCode"`
}

type TheaterManager struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	TheaterID uuid.UUID `json:"theaterId"`
}

type User struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Email           *string   `json:"email"`
	Phone           *string   `json:"phone"`
	PasswordHash    *string   `json:"passwordHash"`
	OauthProvider   *string   `json:"oauthProvider"`
	OauthProviderID *string   `json:"oauthProviderId"`
	Role            string    `json:"role"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}
