// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	pgx_shopspring_decimal "github.com/jackc/pgx-shopspring-decimal"
	"github.com/jackc/pgx/v5/pgtype"
	go_geom "github.com/twpayne/go-geom"
)

type Booking struct {
	ID               uuid.UUID                      `json:"id"`
	UserID           uuid.UUID                      `json:"userId"`
	ShowID           uuid.UUID                      `json:"showId"`
	TotalAmount      pgx_shopspring_decimal.Decimal `json:"totalAmount"`
	Status           string                         `json:"status"`
	PaymentReference string                         `json:"paymentReference"`
	CreatedAt        time.Time                      `json:"createdAt"`
	UpdatedAt        time.Time                      `json:"updatedAt"`
}

type BookingItem struct {
	ID        uuid.UUID                      `json:"id"`
	BookingID uuid.UUID                      `json:"bookingId"`
	SeatID    uuid.UUID                      `json:"seatId"`
	Price     pgx_shopspring_decimal.Decimal `json:"price"`
	CreatedAt time.Time                      `json:"createdAt"`
}

type Format struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Movie struct {
	ID             uuid.UUID   `json:"id"`
	Title          string      `json:"title"`
	LanguageCode   string      `json:"languageCode"`
	Synopsis       pgtype.Text `json:"synopsis"`
	ReleaseDate    time.Time   `json:"releaseDate"`
	RuntimeMinutes pgtype.Int4 `json:"runtimeMinutes"`
	PosterUrl      pgtype.Text `json:"posterUrl"`
	TrailerUrl     pgtype.Text `json:"trailerUrl"`
	Rating         pgtype.Text `json:"rating"`
	CreatedAt      time.Time   `json:"createdAt"`
}

type Screen struct {
	ID         uuid.UUID `json:"id"`
	TheaterID  uuid.UUID `json:"theaterId"`
	Name       string    `json:"name"`
	TotalSeats int32     `json:"totalSeats"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type ScreenFormatCapability struct {
	ScreenID uuid.UUID `json:"screenId"`
	FormatID uuid.UUID `json:"formatId"`
}

type Seat struct {
	ID         uuid.UUID `json:"id"`
	ScreenID   uuid.UUID `json:"screenId"`
	SeatRow    string    `json:"seatRow"`
	SeatNumber int32     `json:"seatNumber"`
	SeatTypeID uuid.UUID `json:"seatTypeId"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"createdAt"`
}

type SeatAllocation struct {
	ShowID    uuid.UUID   `json:"showId"`
	SeatID    uuid.UUID   `json:"seatId"`
	BookingID pgtype.UUID `json:"bookingId"`
	IsBooked  bool        `json:"isBooked"`
}

type SeatType struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"createdAt"`
}

type Show struct {
	ID        uuid.UUID `json:"id"`
	MovieID   uuid.UUID `json:"movieId"`
	ScreenID  uuid.UUID `json:"screenId"`
	StartTime time.Time `json:"startTime"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ShowSeatPricing struct {
	ShowID     uuid.UUID                      `json:"showId"`
	SeatTypeID uuid.UUID                      `json:"seatTypeId"`
	Price      pgx_shopspring_decimal.Decimal `json:"price"`
}

type Theater struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	Address      string        `json:"address"`
	Location     go_geom.Point `json:"location"`
	ContactPhone pgtype.Text   `json:"contactPhone"`
	ContactEmail pgtype.Text   `json:"contactEmail"`
	Status       string        `json:"status"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdatedAt    time.Time     `json:"updatedAt"`
}

type TheaterManager struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	TheaterID uuid.UUID `json:"theaterId"`
}

type User struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	Email           pgtype.Text `json:"email"`
	Phone           pgtype.Text `json:"phone"`
	PasswordHash    pgtype.Text `json:"passwordHash"`
	OauthProvider   pgtype.Text `json:"oauthProvider"`
	OauthProviderID pgtype.Text `json:"oauthProviderId"`
	Role            string      `json:"role"`
	Status          string      `json:"status"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
}
