// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: movie.sql

package repository

import (
	"context"
)

const getMoviesByCity = `-- name: GetMoviesByCity :many
SELECT DISTINCT
    m.id, m.title, m.language_code, m.synopsis, m.release_date, m.runtime_minutes, m.poster_url, m.trailer_url, m.created_at, m.certification, m.rating
FROM movies m
         JOIN shows s ON s.movie_id = m.id
         JOIN screens sc ON sc.id = s.screen_id
         JOIN theaters t ON t.id = sc.theater_id
WHERE t.city_code = $1
  AND s.start_time > now()
  AND s.status != 'cancelled'
ORDER BY m.rating DESC NULLS LAST
LIMIT $2
OFFSET $3
`

type GetMoviesByCityParams struct {
	CityCode string `json:"cityCode"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetMoviesByCity(ctx context.Context, arg GetMoviesByCityParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getMoviesByCity, arg.CityCode, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.LanguageCode,
			&i.Synopsis,
			&i.ReleaseDate,
			&i.RuntimeMinutes,
			&i.PosterUrl,
			&i.TrailerUrl,
			&i.CreatedAt,
			&i.Certification,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
