// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAllUsers(ctx context.Context) ([]User, error)
	GetMoviesByCity(ctx context.Context, arg GetMoviesByCityParams) ([]Movie, error)
	GetShowsByMovieAndCity(ctx context.Context, arg GetShowsByMovieAndCityParams) ([]GetShowsByMovieAndCityRow, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
