// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: show.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	go_geom "github.com/twpayne/go-geom"
)

const getShowsByMovieAndCity = `-- name: GetShowsByMovieAndCity :many
SELECT t.id AS theater_id,
       t.name AS theater_name,
       t.address,
       t.location,

       s.id AS show_id,
       s.start_time,

       f.id AS format_id,
       f.name AS format_name
FROM shows s
         JOIN screens sc ON sc.id = s.screen_id
         JOIN theaters t ON t.id = sc.theater_id
         JOIN formats f ON f.id = s.format_id
WHERE s.movie_id = $1
  AND t.city_code = $2
  AND s.start_time > now()
  AND s.status != 'cancelled'
ORDER BY
    t.name,
    s.start_time
`

type GetShowsByMovieAndCityParams struct {
	MovieID  uuid.UUID `json:"movieId"`
	CityCode string    `json:"cityCode"`
}

type GetShowsByMovieAndCityRow struct {
	TheaterID   uuid.UUID     `json:"theaterId"`
	TheaterName string        `json:"theaterName"`
	Address     string        `json:"address"`
	Location    go_geom.Point `json:"location"`
	ShowID      uuid.UUID     `json:"showId"`
	StartTime   time.Time     `json:"startTime"`
	FormatID    uuid.UUID     `json:"formatId"`
	FormatName  string        `json:"formatName"`
}

func (q *Queries) GetShowsByMovieAndCity(ctx context.Context, arg GetShowsByMovieAndCityParams) ([]GetShowsByMovieAndCityRow, error) {
	rows, err := q.db.Query(ctx, getShowsByMovieAndCity, arg.MovieID, arg.CityCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsByMovieAndCityRow
	for rows.Next() {
		var i GetShowsByMovieAndCityRow
		if err := rows.Scan(
			&i.TheaterID,
			&i.TheaterName,
			&i.Address,
			&i.Location,
			&i.ShowID,
			&i.StartTime,
			&i.FormatID,
			&i.FormatName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
