// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: show.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	go_geom "github.com/twpayne/go-geom"
)

const getShowsByMovieAndCity = `-- name: GetShowsByMovieAndCity :many
SELECT m.id    AS movie_id,
       m.title AS movie_title,
       t.id    AS theater_id,
       t.name  AS theater_name,
       t.address,
       t.location,
       s.id    AS show_id,
       s.start_time,
       f.id    AS format_id,
       f.name  AS format_name
FROM theaters t
         JOIN screens sc ON sc.theater_id = t.id
         JOIN shows s ON s.screen_id = sc.id
         JOIN movies m on m.id = s.movie_id
         JOIN formats f ON f.id = s.format_id
WHERE t.city_code = $1
  AND s.movie_id = $2
  AND s.start_time > now()
  AND s.status != 'cancelled'
ORDER BY t.id, s.start_time
    LIMIT $3
OFFSET $4
`

type GetShowsByMovieAndCityParams struct {
	CityCode string    `json:"cityCode"`
	MovieID  uuid.UUID `json:"movieId"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetShowsByMovieAndCityRow struct {
	MovieID     uuid.UUID     `json:"movieId"`
	MovieTitle  string        `json:"movieTitle"`
	TheaterID   uuid.UUID     `json:"theaterId"`
	TheaterName string        `json:"theaterName"`
	Address     string        `json:"address"`
	Location    go_geom.Point `json:"location"`
	ShowID      uuid.UUID     `json:"showId"`
	StartTime   time.Time     `json:"startTime"`
	FormatID    uuid.UUID     `json:"formatId"`
	FormatName  string        `json:"formatName"`
}

func (q *Queries) GetShowsByMovieAndCity(ctx context.Context, arg GetShowsByMovieAndCityParams) ([]GetShowsByMovieAndCityRow, error) {
	rows, err := q.db.Query(ctx, getShowsByMovieAndCity,
		arg.CityCode,
		arg.MovieID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowsByMovieAndCityRow
	for rows.Next() {
		var i GetShowsByMovieAndCityRow
		if err := rows.Scan(
			&i.MovieID,
			&i.MovieTitle,
			&i.TheaterID,
			&i.TheaterName,
			&i.Address,
			&i.Location,
			&i.ShowID,
			&i.StartTime,
			&i.FormatID,
			&i.FormatName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
